"""Audit of every numerical example in Appendix A (Appendix_IEEE_TECTI.pdf).

For each example the published inputs are recomputed exactly with the
published equations (calibration, u(x), mass assignment, Dempster's rule,
pignistic transform, thresholds 0.38 / 0.11, conflict rule K >= 0.7).
Writes a CSV with published vs. recomputed values and a LaTeX fragment with
the corrected examples.
"""

import csv
import math
import os

from dst_worked_example import K_HIGH, L_CF, L_POA, THETA_EVICT, THETA_UPDATE, U_CF, U_POA, decide

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "results")
EDITS = os.environ.get("DCMF_EDITS_DIR", os.path.join(HERE, "..", "results"))

# (label, PoA, dt, published values as printed in the appendix)
EXAMPLES = [
    ("A.6 (main worked example)", 0.75, 120.0,
     {"CF": 0.301, "m_PoA_C": 0.6183, "m_PoA_E": 0.1752, "m_PoA_T": 0.2065, "m_CF_C": 0.1350, "m_CF_E": 0.7337,
      "m_CF_T": 0.1313, "K": 0.4773, "BetP": 0.3944, "decision": "keep"}),
    ("A.7.1 (high PoA, high CF)", 0.85, 30.0,
     {"CF": 0.7408, "m_PoA_C": 0.728, "m_PoA_E": 0.073, "m_CF_C": 0.694, "m_CF_E": 0.140, "K": 0.153,
      "BetP": 0.874, "decision": "keep"}),
    ("A.7.2 (low PoA, low CF)", 0.12, 300.0,
     {"CF": 0.0498, "m_PoA_C": 0.0, "m_PoA_E": 1.0, "m_CF_C": 0.0, "m_CF_E": 1.0, "K": 0.0, "BetP": 0.0,
      "decision": "evict"}),
    ("A.7.3 as printed (PoA 0.535, dt 102 s)", 0.535, 102.0,
     {"CF": 0.325, "m_PoA_C": 0.35, "m_PoA_E": 0.35, "m_PoA_T": 0.30, "m_CF_C": 0.375, "m_CF_E": 0.375,
      "m_CF_T": 0.25, "K": 0.263, "BetP": 0.505, "decision": "keep"}),
    ("A.8.1 (very high conflict)", 0.90, 500.0, {"CF": 0.0067, "K": 0.82, "decision": "refresh (high conflict)"}),
    ("A.8.2 (PoA above U)", 0.95, 30.0, {"m_PoA_C": 1.0}),
]


def row_for(label, poa, dt, pub):
    r = decide(poa, dt)
    got = {"CF": r["cf"], "m_PoA_C": r["mp"]["C"], "m_PoA_E": r["mp"]["E"], "m_PoA_T": r["mp"]["T"],
           "m_CF_C": r["mc"]["C"], "m_CF_E": r["mc"]["E"], "m_CF_T": r["mc"]["T"], "K": r["K"],
           "BetP": r["betp"], "decision": r["action"]}
    out = []
    for k, v in pub.items():
        g = got[k]
        if isinstance(v, str):
            ok = v == g
            out.append((label, k, v, g, "OK" if ok else "MISMATCH"))
        else:
            ok = (not (isinstance(g, float) and math.isnan(g))) and abs(g - v) <= 0.0025
            out.append((label, k, v, round(g, 4) if not math.isnan(g) else "undefined (K=1)", "OK" if ok else "MISMATCH"))
    return out, r


def main():
    os.makedirs(RES, exist_ok=True)
    os.makedirs(EDITS, exist_ok=True)
    rows = []
    for label, poa, dt, pub in EXAMPLES:
        out, r = row_for(label, poa, dt, pub)
        rows.extend(out)
    # A.7.3 intended example: calibrated p = 0.5 for both metrics
    cf_half = L_CF + 0.5 * (U_CF - L_CF)
    dt_half = -math.log(cf_half) / 0.01
    r = decide(L_POA + 0.5 * (U_POA - L_POA), dt_half)
    rows.append(("A.7.3 intended (p(PoA)=p(CF)=0.5)", "dt giving p(CF)=0.5", "102 s", f"{dt_half:.1f} s (CF = {cf_half:.3f})", "MISMATCH"))
    rows.append(("A.7.3 intended (p(PoA)=p(CF)=0.5)", "BetP", 0.505, round(r["betp"], 4), "MISMATCH"))

    with open(os.path.join(RES, "appendix_a_audit.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["example", "quantity", "published", "recomputed", "status"])
        w.writerows(rows)
    for row in rows:
        if row[-1] != "OK":
            print(" | ".join(str(x) for x in row))

    # LaTeX fragment with the corrected examples
    def ex(label, poa, dt):
        r = decide(poa, dt)
        mp, mc, cb = r["mp"], r["mc"], r["comb"]
        betp = "undefined" if math.isnan(r["betp"]) else f"{r['betp']:.4f}"
        return (f"{label} & {poa:.3f} & {dt:.1f} & {r['cf']:.4f} & "
                f"({mp['C']:.4f}, {mp['E']:.4f}, {mp['T']:.4f}) & ({mc['C']:.4f}, {mc['E']:.4f}, {mc['T']:.4f}) & "
                f"{r['K']:.4f} & {betp} & {r['action']} \\\\")

    lines = [
        "% Auto-generated by revision/analysis/appendix_a_audit.py -- corrected Appendix A examples",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Corrected worked examples for Appendix~A (exact arithmetic; $L_{PoA}=0.15$, $U_{PoA}=0.92$, "
        "$L_{CF}=0.20$, $U_{CF}=0.85$, $u_{max,PoA}=0.30$, $u_{max,CF}=0.25$, $\\lambda=0.01$\\,s$^{-1}$, "
        "$\\theta_{update}=0.38$, $\\theta_{evict}=0.11$, $K_{high}=0.7$). Masses are listed as "
        "$(m(\\mathrm{Cache}), m(\\mathrm{Evict}), m(\\Theta))$.}",
        "\\label{tab:appA_examples}",
        "\\scriptsize",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lcccccccl}",
        "\\toprule",
        "Example & PoA & $\\Delta t$ (s) & CF & $m_{PoA}$ & $m_{CF}$ & $K$ & BetP(Cache) & Decision \\\\",
        "\\midrule",
        ex("A.6 at $\\Delta t=120$\\,s (boundary)", 0.75, 120.0),
        ex("A.6 corrected", 0.75, 135.0),
        ex("A.7.1 high PoA, high CF", 0.85, 30.0),
        ex("A.7.2 low PoA, low CF", 0.12, 300.0),
        ex("A.7.3 $p(PoA)=p(CF)=0.5$", L_POA + 0.5 * (U_POA - L_POA), dt_half),
        ex("A.8.1 very high conflict", 0.90, 500.0),
        ex("A.8.2 PoA above $U_{PoA}$", 0.95, 30.0),
        "\\bottomrule",
        "\\end{tabular}}",
        "\\end{table*}",
    ]
    with open(os.path.join(EDITS, "appendixA_corrected_examples_table.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote results/appendix_a_audit.csv and manuscript_edits/appendixA_corrected_examples_table.tex")


if __name__ == "__main__":
    main()
